---

- name: Pull in OS-specific environment variables
  include_vars: "rhel{{ ansible_distribution_major_version }}.yml"

- name: Install Ruby RPM
  yum:
    name: "ruby-{{ ruby_version }}"
    state: present
    disablerepo: "{{ repo_name }}"
    disable_excludes: "all"

- name: Install/Update Base Ruby Gems
  command: >
    gem update --system
