--- 

- name: Enable ruby module
  command:
    cmd: yum module enable ruby:{{ ruby_minor_version }} --assumeyes
  changed_when: true

- name: Install Ruby RPM
  yum:
    name:
      - ruby
      - ruby-devel
    state: present
    disable_excludes: "all"
